from extensions import (
    URI_DATABASE, SECRET_KEY, APP_DEBUG,
    EMAIL_USER, EMAIL_PASSWORD, EMAIL_FROM,
    SMTP, SMTP_PORT, USE_TLS, USE_SSL,
    SCHEDULER_API_ENABLED
)


class Config:
    SQLALCHEMY_DATABASE_URI = URI_DATABASE
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    API_TITLE = 'Api Rest Interatividade com o Helpdesk.'
    API_VERSION = 'v1'
    OPENAPI_VERSION = '3.0.3'
    SECRET_KEY = SECRET_KEY
    DEBUG = APP_DEBUG
    MAIL_SERVER = SMTP
    MAIL_PORT = SMTP_PORT
    MAIL_USE_TLS = USE_TLS
    MAIL_USE_SSL = USE_SSL
    MAIL_USERNAME = EMAIL_USER
    MAIL_PASSWORD = EMAIL_PASSWORD
    MAIL_DEFAULT_SENDER = EMAIL_FROM
    SCHEDULER_API_ENABLED = SCHEDULER_API_ENABLED

class ConfigDebug(Config):
    OPENAPI_URL_PREFIX = "/"
    OPENAPI_SWAGGER_UI_PATH = "/swagger-ui"
    OPENAPI_SWAGGER_UI_URL = 'https://cdn.jsdelivr.net/npm/swagger-ui-dist/'