from .login.login_view import blp as login_view
from .profile.profile_api import blp as profile_api
from .login.login_api import blp as login_api
from .sector.sector_api import blp as sector_api
from .sector.sector_view import blp as sector_view
from .utils.bucket_route import bucket as bucket_view
from .manager_user.manager_user_api import blp as manager_user_api
from .manager_user.manager_user_view import blp as manager_user_view
from .config_helpdesk.config_helpdesk_api import blp as config_helpdesk_api
from .helpdesk.helpdesk_api import blp as helpdesk_api
from .helpdesk.helpdesk_view import blp as helpdesk_view
from .helpdesk.helpdesk_assuntos_api import blp as helpdesk_assunto_api