from .user_table import User
from .sector_table import Sector
from .config_table import ConfigTable
from .ticket_table import Ticket
from .ticket_anexos_table import TicketAnexos
from .ticket_assunto_table import TicketAssunto
from .ticket_copia_table import TicketCopia
from .ticket_interacao_table import TicketInteracao
from .ticket_status_table import TicketStatus
from .ticket_status_de_para_table import TicketStatusDePara